/* Generated by client/main.py. Do not edit by hand. */
#pragma once

#define PRESET_DEFAULT_MIDI_MSG { .type = MIDI_MSG_NONE, .channel = 0, .data1 = 0, .data2 = 0, .is_tx = 1, .uart_num = 1 }
#define PRESET_DEFAULT_INIT { \
    .relay_flags = 0, \
    .button_flags = {0, 0, 0, 0}, \
    .extra_btn_modes = {0, 0, 0, 0}, \
    .exp_channel = 0, \
    .exp_cc_num = 11, \
    .midi_msgs = { [0 ... 9] = PRESET_DEFAULT_MIDI_MSG } \
}

static const Preset preset_seed[TOTAL_PRESETS] = {
    //[0 ... TOTAL_PRESETS - 1] = PRESET_DEFAULT_INIT,
    [0] = {
        .relay_flags = 0x2B54,
        .button_flags = {0, 0, 0, 0},
        .extra_btn_modes = {0, 0, 0, 0},
        .exp_channel = 0,
        .exp_cc_num = 11,
        .midi_msgs = {
            [0] = { .type = MIDI_MSG_NONE, .channel = 0, .data1 = 0, .data2 = 0, .is_tx = 1, .uart_num = 1 },
            [1] = { .type = MIDI_MSG_NONE, .channel = 0, .data1 = 0, .data2 = 0, .is_tx = 1, .uart_num = 1 },
            [2] = { .type = MIDI_MSG_NONE, .channel = 0, .data1 = 0, .data2 = 0, .is_tx = 1, .uart_num = 1 },
            [3] = { .type = MIDI_MSG_NONE, .channel = 0, .data1 = 0, .data2 = 0, .is_tx = 1, .uart_num = 1 },
            [4] = { .type = MIDI_MSG_NONE, .channel = 0, .data1 = 0, .data2 = 0, .is_tx = 1, .uart_num = 1 },
            [5] = { .type = MIDI_MSG_NONE, .channel = 0, .data1 = 0, .data2 = 0, .is_tx = 1, .uart_num = 1 },
            [6] = { .type = MIDI_MSG_NONE, .channel = 0, .data1 = 0, .data2 = 0, .is_tx = 1, .uart_num = 1 },
            [7] = { .type = MIDI_MSG_NONE, .channel = 0, .data1 = 0, .data2 = 0, .is_tx = 1, .uart_num = 1 },
            [8] = { .type = MIDI_MSG_NONE, .channel = 0, .data1 = 0, .data2 = 0, .is_tx = 1, .uart_num = 1 },
            [9] = { .type = MIDI_MSG_NONE, .channel = 0, .data1 = 0, .data2 = 0, .is_tx = 1, .uart_num = 1 }
        },
    }, /* A1 */
};

#undef PRESET_DEFAULT_MIDI_MSG
#undef PRESET_DEFAULT_INIT
